name: Release

on: workflow_dispatch

jobs:
  build-win-x64:
    runs-on: windows-2019
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          cache: true
          update: true
          install: >-
            make
            zip
          pacboy: >-
            gcc:p
      - name: Get Version
        id: get-version
        run: |
          VERSION=git describe --tags --abbrev=0
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version is \"${{ env.VERSION }}\""
      - name: Build
        run: make package
      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            ideapad_keyboard_backlight_${{ env.VERSION }}.zip
